# Python CircleCI 2.0 configuration file.
version: 2
jobs:
  build:
    docker:
      - image: circleci/python3.8
  working_directory: ~/repo
  steps:
  # Step 1: obtain repo from GitHub
  - checkout
  # Step 2: create venv and install dependencies
  - run:
  name: install dependencies
  command: |
  sudo pip install pipenv
  pipenv install
  python3 -m venv venv
  source venv/bin/activate
  pip install requirement.txt
  # Step 3: run linter and tests
  - run:
  name: run tests
  command: |
  source venv/bin/activate
  flake8 --exclude=venv* --statistics
  pytest -v --cov = calculator
